Made `split_token` non async, as it doesn't need to be, and that way we can call it from a normal method.
Solves:
    self.is_api, self.user_id, self.secret = split_token(api_key)
TypeError: cannot unpack non-iterable coroutine object